# Generated by Django 5.0 on 2024-01-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_cartdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdb',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
