# Generated by Django 5.0 on 2024-01-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_wishlistdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistdb',
            name='uname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
