# Generated by Django 5.0 on 2024-04-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_billdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistdb',
            name='pid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
