# Generated by Django 5.0 on 2023-12-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(blank=True, max_length=100, null=True)),
                ('fees', models.IntegerField(blank=True, null=True)),
                ('teacher', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
