# Generated by Django 5.0 on 2023-12-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manu', '0003_categorydb_rename_cdb_itemdb_delete_rdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemdb',
            old_name='course_name',
            new_name='cname',
        ),
        migrations.RenameField(
            model_name='itemdb',
            old_name='duration',
            new_name='iname',
        ),
        migrations.RenameField(
            model_name='itemdb',
            old_name='fees',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='itemdb',
            name='teacher',
        ),
        migrations.AddField(
            model_name='itemdb',
            name='details',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='itemdb',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='itemdb',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
